# Generated by Django 5.1 on 2024-10-19 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('environmental', 'Environmental'), ('educational', 'Educational'), ('community_service', 'Community Service'), ('interfaith', 'Interfaith')], max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('age_requirement', models.CharField(max_length=100)),
                ('attendees', models.IntegerField(default=0)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.volunteeropportunity')),
            ],
        ),
    ]
