# Generated by Django 5.1 on 2024-10-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
