# Generated by Django 5.1 on 2024-10-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_prayerrequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
