# Generated by Django 5.1 on 2024-10-21 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_contact_alter_userprofile_initiative_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='initiative',
            field=models.ForeignKey(default=0.0010375494071146246, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.charity'),
            preserve_default=False,
        ),
    ]
