# Generated by Django 5.1 on 2024-10-22 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_festival_alter_userprofile_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='contact_info',
            field=models.CharField(max_length=255, default='N/A'),  # Default to 'N/A'
            
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.charity'),
        
        ),
    ]
