# Generated by Django 5.1 on 2024-10-22 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_helprequest_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='initiative',
            field=models.ForeignKey(default=0.0010869565217391304, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.charity'),
            preserve_default=False,
        ),
    ]
