# Generated by Django 5.1 on 2024-10-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_helprequest_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health Support'), ('food_assistance', 'Food Assistance'), ('shelter_services', 'Shelter Services'), ('educational_support', 'Educational Support')], max_length=50)),
                ('description', models.TextField()),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        
        migrations.AddField(
            model_name='helprequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.charity'),
            
        ),
    ]
