# Generated by Django 5.1 on 2024-10-22 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_helprequest_address_helprequest_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='contact_info',
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.charity'),
            
        ),
    ]
